//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinicEntities : DbContext
    {
        public clinicEntities()
            : base("name=clinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Examinations> Examinations { get; set; }
        public virtual DbSet<LaboratoryExamination> LaboratoryExamination { get; set; }
        public virtual DbSet<LaboratoryPerson> LaboratoryPerson { get; set; }
        public virtual DbSet<LaboratorySupervisor> LaboratorySupervisor { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PhysicalExamination> PhysicalExamination { get; set; }
        public virtual DbSet<RegistrationPerson> RegistrationPerson { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
