//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Doctor = new HashSet<Doctor>();
            this.LaboratoryPerson = new HashSet<LaboratoryPerson>();
            this.LaboratorySupervisor = new HashSet<LaboratorySupervisor>();
            this.RegistrationPerson = new HashSet<RegistrationPerson>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> dt_AccountValidityFrom { get; set; }
        public Nullable<System.DateTime> dt_AccountValidityTo { get; set; }
        public int PersonId { get; set; }
        public string Phone_Number { get; set; }
        public string Login { get; set; }
        public string Position { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctor { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryPerson> LaboratoryPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratorySupervisor> LaboratorySupervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationPerson> RegistrationPerson { get; set; }
    }
}
