//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryExamination
    {
        public int Id { get; set; }
        public string Doctor_Note { get; set; }
        public System.DateTime dt_Request { get; set; }
        public string Result { get; set; }
        public System.DateTime dt_Complete_Cancel { get; set; }
        public string Supervisor_Note { get; set; }
        public System.DateTime dt_Confirmation { get; set; }
        public string Status { get; set; }
        public string ExaminationCode { get; set; }
        public Nullable<int> LabPersonId { get; set; }
        public Nullable<int> LabSupervisorId { get; set; }
        public int AppointmentId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Examinations Examinations { get; set; }
        public virtual LaboratoryPerson LaboratoryPerson { get; set; }
        public virtual LaboratorySupervisor LaboratorySupervisor { get; set; }
    }
}
